<?php
return [
  [
    'pid'   => 3,
    'title' => '短信服务',
    'icon' => 'typcn typcn-messages',
    'module' => 'plugins.sms',
    'url' => 'system/plugins/run',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 0,
    'childs' => [
      [
        'title' => '短信平台',
        'icon' => 'fa fa-gear',
        'module' => 'plugins.sms',
        'url' => 'system/plugins/run',
        'param' => '_a=index&_c=index&_p=sms',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '网关配置',
            'icon' => '',
            'module' => 'plugins.sms',
            'url' => 'system/plugins/run',
            'param' => '_a=config&_c=index&_p=sms',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'sort' => 0,
          ],
          [
            'title' => '默认设置',
            'icon' => '',
            'module' => 'plugins.sms',
            'url' => 'system/plugins/run',
            'param' => '_a=def&_c=index&_p=sms',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'sort' => 0,
          ],
          [
            'title' => '状态设置',
            'icon' => '',
            'module' => 'plugins.sms',
            'url' => 'admin/plugins/status',
            'param' => '_a=status&_c=index&_p=sms',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '短信模板',
        'icon' => 'fa fa-envelope',
        'module' => 'plugins.sms',
        'url' => 'system/plugins/run',
        'param' => '_a=index&_c=template&_p=sms',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '删除模板',
            'icon' => '',
            'module' => 'plugins.sms',
            'url' => 'system/plugins/run',
            'param' => '_a=del&_c=template&_p=sms',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '短信日志',
        'icon' => 'fa fa-list-ul',
        'module' => 'plugins.sms',
        'url' => 'system/plugins/run',
        'param' => '_a=index&_c=logs&_p=sms',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '删除日志',
            'icon' => '',
            'module' => 'plugins.sms',
            'url' => 'system/plugins/run',
            'param' => '_a=del&_c=logs&_p=sms',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
