<?php
return [
  [
    'title' => '新闻管理',
    'icon' => 'aicon ai-shezhi',
    'module' => 'news',
    'url' => 'news',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '新闻管理',
        'icon' => 'aicon ai-tishi',
        'module' => 'news',
        'url' => 'news/index/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 1,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '新闻列表',
            'icon' => 'aicon ai-caidan',
            'module' => 'news',
            'url' => 'news/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '增加',
                'icon' => 'aicon ai-tianjia',
                'module' => 'news',
                'url' => 'news/index/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => 'aicon ai-error',
                'module' => 'news',
                'url' => 'news/index/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => 'aicon ai-jinyong',
                'module' => 'news',
                'url' => 'news/index/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
