<?php
return [
  [
    'title' => '广告管理',
    'icon' => 'aicon ai-shezhi',
    'module' => 'banner',
    'url' => 'banner',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 102,
    'childs' => [
      [
        'title' => '广告管理',
        'icon' => '',
        'module' => 'banner',
        'url' => 'banner/banner/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '轮播图广告',
            'icon' => 'typcn typcn-chart-bar-outline',
            'module' => 'banner',
            'url' => 'banner/banner/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'banner',
                'url' => 'banner/banner/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '启动广告图',
            'icon' => 'typcn typcn-chart-bar-outline',
            'module' => 'banner',
            'url' => 'banner/banner/indexad',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'banner',
                'url' => 'banner/banner/addad',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '首页广告',
            'icon' => 'typcn typcn-chart-bar-outline',
            'module' => 'banner',
            'url' => 'banner/banner/indexHomeAd',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'banner',
                'url' => 'banner/banner/addad',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '播放页弹窗广告',
            'icon' => 'typcn typcn-chart-bar-outline',
            'module' => 'banner',
            'url' => 'banner/banner/indexPlayerAd',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'banner',
                'url' => 'banner/banner/addad',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '播放页底部广告',
            'icon' => 'typcn typcn-chart-bar-outline',
            'module' => 'banner',
            'url' => 'banner/banner/publicAd',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'banner',
                'url' => 'banner/banner/addad',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '视频播放前广告',
            'icon' => 'typcn typcn-chart-bar-outline',
            'module' => 'banner',
            'url' => 'banner/banner/videoAd',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'banner',
                'url' => 'banner/banner/addad',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
