<?php
return [
  [
    'title' => '网络电视',
    'icon' => 'aicon ai-shezhi',
    'module' => 'live',
    'url' => 'live',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '网络电视',
        'icon' => 'typcn typcn-eye-outline',
        'module' => 'live',
        'url' => 'live/index/categoryList',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '电视栏目',
            'icon' => 'typcn typcn-eye-outline',
            'module' => 'live',
            'url' => 'live/index/categoryList',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '节目清单',
            'icon' => 'typcn typcn-social-tumbler-circular',
            'module' => 'live',
            'url' => 'live/index/liveList',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
